### ISSUE TITLE
Does not currently work on HTC One VX

### ISSUE THREAD

**Issue by Unh0lyTigg** [mauimauer/cheapcast#3]
Clicking the Start Service button crashes the app with a stacktrace:

```
java.lang.NullPointerException
    at at.maui.cheapcast.Utils.getLocalV4Address(Utils.java:70)
    at at.maui.cheapcast.ssdp.SSDP.run(SSDP.java:84)
```

That's really all there is. Excellent app otherwise.

**Comment by Unh0lyTigg** [comment]
One of the latest updates fixed this, closing.
