### ISSUE TITLE
Services crashes when trying to cast YT video to HP Touchpad

### ISSUE THREAD

**Issue by sebaroesch** [mauimauer/cheapcast#4]
Hi,

the service crashes immediately, see the log:

```
I/ActivityManager(  227): START {dat=https://www.youtube.com/tv?pairingCode=65dc243f-41dd-4734-9e1e-7455326e9b90&v=KMmiWds-Pcs&t=0 flg=0x10000000 cmp=at.maui.cheapcast/.activity.CastActivity (has extras)} from pid 25067
E/AndroidRuntime(25882): FATAL EXCEPTION: main
E/AndroidRuntime(25882): java.lang.NoSuchMethodError: android.webkit.WebSettings.setAllowFileAccessFromFileURLs
E/AndroidRuntime(25882):    at at.maui.cheapcast.activity.CastActivity.onCreate(CastActivity.java:83)
E/AndroidRuntime(25882):    at android.app.Activity.performCreate(Activity.java:4465)
E/AndroidRuntime(25882):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
E/AndroidRuntime(25882):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2033)
E/AndroidRuntime(25882):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
E/AndroidRuntime(25882):    at android.app.ActivityThread.access$600(ActivityThread.java:132)
E/AndroidRuntime(25882):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1157)
E/AndroidRuntime(25882):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25882):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(25882):    at android.app.ActivityThread.main(ActivityThread.java:4575)
E/AndroidRuntime(25882):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25882):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(25882):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(25882):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(25882):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  227):   Force finishing activity at.maui.cheapcast/.activity.CastActivity
W/ActivityManager(  227):   Force finishing activity at.maui.cheapcast/.activity.PreferenceActivity
W/ActivityManager(  227): Activity pause timeout for ActivityRecord{2c08b078 at.maui.cheapcast/.activity.CastActivity}
I/WindowManager(  227): WIN DEATH: Window{2bdf2ca8 at.maui.cheapcast/at.maui.cheapcast.activity.PreferenceActivity paused=true}
I/ActivityManager(  227): Process at.maui.cheapcast (pid 25882) has died.
W/ActivityManager(  227): Activity destroy timeout for ActivityRecord{2bbe8570 at.maui.cheapcast/.activity.PreferenceActivity}
```

Running 4.0.4 on a HP Touchpad.

Thanks for your work and for providing it for free!

**Comment by renenoel** [comment]
I had a similar problem with the Touchpad: I tried playing Google Play Music from the tablet to my Nexus 4, and it crashed. Same thing playing it from the Nexus 4 to the Touchpad.

**Comment by sebaroesch** [comment]
I can´t tell what you changed to fix it from the changelog inside the app, but I was able to cast some YT videos and music (via Play Music) to Cheapcast v0.3 runnning on the Touchpad.

It still crashes / freezes from time to time, but that might be due to some general glitches I guess.

Thanks again, hope to see the source here on GitHub some day :)
